[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"
buildTarget = "runner"

[deploy]
startCommand = "node server.js"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[deploy.healthcheck]
path = "/"
interval = 30
timeout = 10
